name = "sts-generator"
main = "src/index.ts"
compatibility_date = "2023-01-25"
routes = [
	{ pattern = "sts.lenster.xyz", custom_domain = true }
]
keep_vars = true

[env.production.vars]
EVER_ACCESS_KEY = "756f9caa465b4366ab0221f30627183d"
EVER_ACCESS_SECRET = "4A4DfLPI221uHwmE73AxZ72TqiLviz4vjH8KfTGw"
